networks:
  # enable connection with Traefik
  traefik_default:
    external: true

services:
  odoo-db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - traefik_default

  odoo-app:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}:${WEB_IMAGE_TAG}
    restart: always
    depends_on:
      - odoo-db
    ports:
      - "${WEB_PORT}:8069"
    #tty: true
    #command: -- --dev=reload
    environment:
      - HOST=odoo-db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWD}
    networks:
      - traefik_default
    volumes:
      - odoo-app-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/addons
      - ./extra-addons:/mnt/extra-addons
      - ./scripts:/mnt/scripts
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo-app.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.odoo-app.entrypoints=web
      - traefik.http.services.odoo-app.loadbalancer.server.port=8069
volumes:
  odoo-db-data:
  odoo-app-data:



  
