version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    restart: always
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/jdownloader-2:/config:rw"
      - "/home/oem/storage/containers/Downloads:/output:rw"

