WEBPASSWORD=c65f4e580c842d880a598f4f44bc7bc13bc4c99fc5f9ff8100d58ca79d2e1089
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
BLOCKING_ENABLED=true
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=
IPV4_ADDRESS=0.0.0.0
IPV6_ADDRESS=
DNS_BOGUS_PRIV=
DNS_FQDN_REQUIRED=
DNSSEC=
CONDITIONAL_FORWARDING=
CONDITIONAL_FORWARDING_IP=
CONDITIONAL_FORWARDING_DOMAIN=
CONDITIONAL_FORWARDING_REVERSE=
PIHOLE_INTERFACE=eth0
