version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Argentina/Buenos Aires'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      WEBPASSWORD: 'secretpass'
      INTERFACE: 'eno1'
      DNSMASQ_USER: 'pihole'
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # first always should be 127.0.0.1 the second here should be your router or
    # a public available DNS. Those are not your pihole upstream servers later used!
    # The pihole upstream servers can be configured in the GUI Later.
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    restart: unless-stopped

