services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.portainer.rule=PathPrefix(`/`)
    #  - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true

volumes:
  portainer_data:
